### PR TITLE
feat: CI/CD build on pull request

### PR DESCRIPTION
**Pull request by R0Wi**
Like mentioned in https://github.com/forcedotcom/SFDX-Data-Move-Utility/pull/621#issuecomment-1660865636 it would be good to have a CI/CD build to make sure we don't merge anything which does not compile.

### CODE REVIEW

**Comment by bgandin** [comment]
Might be better to have this run on all pushes as well, rather than just pull requests.

**Comment by R0Wi** [comment]
@bgandin I checked [this file](https://github.com/forcedotcom/SFDX-Data-Move-Utility/blob/d4f0c7e64141aa75b036f76b85f08774892967b5/.github/workflows/onPushToMain.yml) and it seems like there is already a release process going on if a new push to `master` was made. The creation of the release triggers a `npm` push [here](https://github.com/forcedotcom/SFDX-Data-Move-Utility/blob/d4f0c7e64141aa75b036f76b85f08774892967b5/.github/workflows/onRelease.yml#L15C11-L15C11) which later builds the app [here](https://github.com/salesforcecli/github-workflows/blob/74e797c3d7570541a36a25359691f744f343515f/.github/workflows/npmPublish.yml#L90). So everytime there is a push to `master`, there is also a build being triggered.

In my opinion it's okay to only build the `master` since private feature branches might not be ready before bringing them in via pull request. What do you mean?

**Comment by R0Wi** [comment]
Adjusted the workflow to match https://github.com/salesforcecli/github-workflows/blob/74e797c3d7570541a36a25359691f744f343515f/.github/workflows/npmPublish.yml#L82-L91

**Comment by hknokh** [comment]
Hello,
 I want to clarify that I prefer not to modify actions/workflows since they are maintained by the Salesforce SFDX-CLI team, not me. As a contributor, it is your responsibility to test whether the feature compiles on your local machine before submitting a pull request. Unfortunately, I cannot approve this pull request at the moment.
Thank you for your understanding.
Best regards

**Pull request closed without merging**
