### PR TITLE
feat: Add parameter for query poll timeout

### PR DESCRIPTION
**Pull request by R0Wi**
**Background**

When querying a huge amount of data or when using complex queries via SF Bulk API, it can happen that queries take more than the currently hardcoded amount of 4 minutes to complete. This can happen especially when SF is currently under heavy load.

image

SFDMU will then quit with the following error:

image

**Introducing the `pollingQueryTimeoutMs` parameter**

By introducing a parameter for the query timout, this problem can be mitigated.

`export.json`

```json
{
  "pollingQueryTimeoutMs": 600000, // timeout = 10 minutes
  "objects": [
     {
           "query": "SELECT Id, readonly_false FROM ..."
     }
   ]
}

```

**Implementation**

* Add new script property "pollingQueryTimeoutMs"
* Default timeout is still 4 minutes (backward compat)
* Use timeout only for bulk query, not yet for CRUD operations

**Missing**

- [ ] Documentation (similar to `pollingIntervalMs`)
- [ ] Testing when query is used in deletion process ( `deleteOldData = true`)

### CODE REVIEW

**Comment by hknokh** [comment]
Hello,
I took a look at your code, and from a brief inspection, it seems to be okay. Have you compiled and tested it locally on your machine?
Kindly let me know about your local testing results.
Best regards

**Comment by R0Wi** [comment]
Yes I did test pulling data into CSV files and this worked as expected. Build was also successful. Like mentioned above, what needs to be done is documenting the new param and maybe do some tests for deleting objects in an org because I saw that the query function is used there, too.

**Comment by hknokh** [comment]
Thank you for confirming that.
I will make tests and will merge if it's ok.

**Comment by hknokh2** [comment]
I would greatly appreciate it if you could complete all the tests on your end, including deletions. This would expedite the processing of the merge request. Thank you in advance.

**Comment by R0Wi** [comment]
Data retrival before deletion seem to work, too. If I run an upload with the following `export.json`

```json
{
  "pollingQueryTimeoutMs": 300000,
  "promptOnIssuesInCSVFiles" : false,
  "promptOnMissingParentObjects" : false,
  "excludeIdsFromCSVFiles": true,
	"objects": [
		{
            "query": "SELECT Id, readonly_false FROM Product2",
	    "operation": "Upsert",
            "externalId": "ExternalId__c",
            "deleteOldData": true
        }
  ]
}

```

I get:

```
DELETING OLD DATA FROM THE TARGET ...
=================

[15:16:24.95] {Product2} Deleting old records from the Target ...
[15:17:57.514] {Product2} The Delete API operation has been started using Bulk API V2.0.
[15:23:51.705] [WARN] [Batch# 750MU000000Ax9IYAS:Delete] {Product2} Completed [...]
```

So working as expected 👍

**Comment by hknokh** [comment]
Hello
Merged.
Thank you very much for your work.

**Comment by R0Wi** [comment]
Is there any open source possibility to update the docs accordingly? Or are you maintaining the docs closed source?

**Comment by hknokh2** [comment]
There is no open source for the doc. 
I'm maintaining the doc and it's appears  up-to-date. 
Currently I have no time to tackle this, however I will do it ASAP

**Pull request merged**
