### PR TITLE
Badwords filter updates

### PR DESCRIPTION
**Pull request by nvuillam**
- display number of remaining records
- arrange messages to avoid doubling SObject identifiers in logs
- control badwords file format

### CODE REVIEW

**Comment by hknokh** [comment]
Thx for the update.
I've added your modifications from my side in the today's plugin release.
This PR is closed.

**Comment by nvuillam** [comment]
Why not merging my PR ? I'm a little bit sad to not appear in the repo contributors haha :)

**Comment by hknokh** [comment]
Apologize for that.
But currently there was 2  practical reasons why I didn't merged your code as is:
1) I had to update also the package.json, not only the code, otherwise the Plugin version will not be deployed and signed by the Salesforce DX security authority.
2) The second reason is, exactly at the same time I was making a modifications at the same / related pieces of code and wanted to release all together to get things arranged well.
Anyway I confirm that you made the most of work ), my contribution seems to be much more modest to refactor the already built source code.
Thx again.

**Comment by nvuillam** [comment]
No problem, the most important is that the addOn is live and that we can use it , thanks a lot for that :)

**Pull request closed without merging**
